/-
Copyright (c) 2026 Gabriel Dahia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gabriel Dahia
-/
import DenseSetsWithoutLargeSumsets.Combinatorics.Additive.Chang.Model

/-! # Effective lattice coordinates for box reboxing

This file transports a finite set `D ⊆ ℤ^d` to the saturated lattice in its real span, whose rank
is the effective dimension of `D`. The coordinate and reconstruction maps are reusable in the
specialized projection and slice reboxing arguments.
-/

namespace DenseSetsWithoutLargeSumsets

noncomputable section

variable {d : ℕ} (D : Finset (Fin d → ℤ))

open Classical in
/-- Integer coordinates in the saturated lattice generated by `D`, extended by zero away from its
real span. -/
noncomputable def effectiveLatticeMap (y : Fin d → ℤ) :
    Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ :=
  if hy : y ∈ latticeDomain D then
    integerGeneratedLatticeCoordHom D (latticeEmbed D ⟨y, hy⟩)
  else 0

lemma effectiveLatticeMap_eq_on {y : Fin d → ℤ} (hy : y ∈ latticeDomain D) :
    effectiveLatticeMap D y =
      integerGeneratedLatticeCoordHom D (latticeEmbed D ⟨y, hy⟩) := by
  unfold effectiveLatticeMap
  rw [dite_eq_left hy]

lemma intVectorToReal_effectiveLatticeMap {y : Fin d → ℤ} (hy : y ∈ latticeDomain D) :
    intVectorToReal (effectiveLatticeMap D y) =
      integerGeneratedCoordinateEquiv D (latticeEmbed D ⟨y, hy⟩) := by
  rw [effectiveLatticeMap_eq_on D hy]
  ext i
  rw [intVectorToReal, integerGeneratedCoordinateEquiv_apply_lattice,
    integerGeneratedLatticeCoordHom_apply]

/-- The effective rank of a finite set of integer vectors. -/
abbrev effectiveRank : ℕ := Module.finrank ℝ (integerGeneratedSubspace D)

/-- The set `D` in saturated-lattice coordinates. -/
noncomputable def effectiveLatticeCoords : Finset (Fin (effectiveRank D) → ℤ) :=
  D.image (effectiveLatticeMap D)

/-- The real casts of the effective lattice coordinates span their full coordinate space. -/
lemma span_intVectorToReal_effectiveLatticeCoords_eq_top :
    Submodule.span ℝ
      (↑((effectiveLatticeCoords D).image intVectorToReal) :
        Set (Fin (effectiveRank D) → ℝ)) = ⊤ := by
  let H := integerGeneratedSubspace D
  let e : H ≃ₗ[ℝ] Fin (effectiveRank D) → ℝ := integerGeneratedCoordinateEquiv D
  set T : Finset (Fin (effectiveRank D) → ℝ) :=
    (effectiveLatticeCoords D).image intVectorToReal with hT
  set Z : Set H := {p : H | ∃ y ∈ (D : Set (Fin d → ℤ)), ↑p = intVectorToReal y}
  have hT_eq : (T : Set (Fin (effectiveRank D) → ℝ)) = e '' Z := by
    ext x
    constructor
    · intro hx
      rw [hT, Finset.coe_image, effectiveLatticeCoords, Finset.coe_image] at hx
      obtain ⟨v, ⟨y, hyD, rfl⟩, rfl⟩ := hx
      refine ⟨⟨intVectorToReal y, mem_latticeDomain_of_mem D hyD⟩,
        ⟨y, hyD, rfl⟩, ?_⟩
      rw [intVectorToReal_effectiveLatticeMap D
        (mem_latticeDomain_of_mem D hyD)]
      rfl
    · rintro ⟨p, ⟨y, hyD, hp⟩, rfl⟩
      rw [hT, Finset.coe_image, effectiveLatticeCoords, Finset.coe_image]
      refine ⟨effectiveLatticeMap D y, ⟨y, hyD, rfl⟩, ?_⟩
      rw [intVectorToReal_effectiveLatticeMap D
        (mem_latticeDomain_of_mem D hyD)]
      congr 1
      apply Subtype.ext
      exact hp.symm
  have hsubtype_image : H.subtype '' Z = intVectorToReal '' (D : Set (Fin d → ℤ)) := by
    ext x
    constructor
    · rintro ⟨p, ⟨y, hyD, hpy⟩, rfl⟩
      exact ⟨y, hyD, hpy.symm⟩
    · rintro ⟨y, hyD, rfl⟩
      exact ⟨⟨intVectorToReal y, mem_latticeDomain_of_mem D hyD⟩,
        ⟨y, hyD, rfl⟩, rfl⟩
  have hspanZ : Submodule.span ℝ Z = ⊤ := by
    apply Submodule.map_injective_of_injective H.subtype_injective
    rw [Submodule.map_top, Submodule.range_subtype, Submodule.map_span, hsubtype_image]
    rfl
  rw [hT, hT_eq]
  have hmap : Submodule.span ℝ (e '' Z) =
      Submodule.map e.toLinearMap (Submodule.span ℝ Z) :=
    (Submodule.map_span e.toLinearMap Z).symm
  rw [hmap, hspanZ, Submodule.map_top, LinearEquiv.range]

end

end DenseSetsWithoutLargeSumsets
