/-
Copyright (c) 2026 Gabriel Dahia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gabriel Dahia
-/
import Mathlib.Analysis.Real.Pi.Bounds
import DenseSetsWithoutLargeSumsets.Combinatorics.Additive.Chang.Fourier
import DenseSetsWithoutLargeSumsets.Combinatorics.Additive.Chang.Properization

/-! # A large progression inside a chord neighborhood

This file proves the geometric step between the Fourier stage and the packing stage of Chang's
argument: the neighborhood of a finite set of frequencies contains a *proper* progression of
comparable size.

The neighborhood is the chord set `{x | ∀ ψ ∈ Δ, ‖1 - ψ x‖ ≤ ε}` of `Chang.Fourier`. Writing
`ψⱼ x = e (rⱼ x / q)`, chord width is controlled by the integer representatives of the products
`rⱼ x`, so the construction is carried out for the explicit lattice

```text
freqLattice r = {(x, a₁, …, a_k) ∈ ℤ ^ (k + 1) | aⱼ ≡ rⱼ x (mod q)}
```

inside the box `freqBox q D` of half-widths `(q, D, …, D)`. The pieces are:

- `exists_adapted_shortFamily` of `Chang.GeometryOfNumbers` gives `k + 1` independent lattice
  vectors `v₀, …, v_k` with `vᵢ` short for the `i`-th successive minimum `λᵢ` of that box;
- the progression is generated by the first coordinates of the `vᵢ`, with the coefficient of `vᵢ`
  ranging over `[-Lᵢ, Lᵢ]` for `Lᵢ = ⌊1 / (4 (k + 1) λᵢ)⌋`. The choice of `Lᵢ` keeps every
  combination inside *half* the box, which gives both the Bohr certificate and, since the first
  coordinate then cannot wrap around `q`, properness;
- the size is read off from the two lattice point counts: the pigeonhole lower bound
  `exists_card_lt_forall_mem_ker_of_mul_card_lt` and the successive-minima upper bound
  `BoxLattice.ncard_latticeBoxPoints_le`.

The main results are `exists_proper_gap_of_freqLattice`, in the arithmetic formulation, and
`exists_proper_gap_chordSet`, its chord-width consequence.

Primality of `q` is not used anywhere in this file: the lattice has index `q ^ k` in `ℤ ^ (k + 1)`
whatever `q` is, and no nonzero modular scalar has to be cancelled. Room is explicit throughout:
every reduction modulo `q` performed here goes through `eq_zero_of_dvd_of_two_mul_abs_le`, which
consumes the bound placing the relevant lattice vector inside half the box.
-/

namespace DenseSetsWithoutLargeSumsets

open scoped Pointwise

noncomputable section

section FrequencyLattice

variable {q k : ℕ}

/-- The homomorphism measuring the failure of an integer vector `(x, a₁, …, a_k)` to satisfy the
congruences `aⱼ ≡ rⱼ x (mod q)`. -/
def freqHom (r : Fin k → ZMod q) : (Fin (k + 1) → ℤ) →+ (Fin k → ZMod q) where
  toFun v j := ((v j.succ : ℤ) : ZMod q) - r j * ((v 0 : ℤ) : ZMod q)
  map_zero' := by
    funext j
    simp
  map_add' u v := by
    funext j
    simp only [Pi.add_apply]
    push_cast
    ring

/-- The lattice of integer vectors whose frequency coordinates represent the corresponding
multiples of the first coordinate. -/
def freqLattice (r : Fin k → ZMod q) : AddSubgroup (Fin (k + 1) → ℤ) := (freqHom r).ker

lemma mem_freqLattice {r : Fin k → ZMod q} {v : Fin (k + 1) → ℤ} :
    v ∈ freqLattice r ↔ ∀ j, ((v j.succ : ℤ) : ZMod q) = r j * ((v 0 : ℤ) : ZMod q) := by
  simp [freqLattice, AddMonoidHom.mem_ker, funext_iff, freqHom, sub_eq_zero]

/-- The box measuring the lattice: a whole period in the first coordinate and the allowed
frequency width in the others. -/
def freqBox (q D : ℕ) : Fin (k + 1) → ℕ := Fin.cases q fun _ ↦ D

@[simp] lemma freqBox_zero (q D : ℕ) : freqBox (k := k) q D 0 = q := rfl

@[simp] lemma freqBox_succ (q D : ℕ) (j : Fin k) : freqBox q D j.succ = D := rfl

lemma freqBox_pos {D : ℕ} (hq : 0 < q) (hD : 0 < D) : ∀ i, 0 < freqBox (k := k) q D i :=
  Fin.cases hq fun _ ↦ hD

/-- The lattice contains `q ℤ ^ (k + 1)`, so all its successive minima with respect to the box are
defined and positive. -/
lemma hasIndependentShort_freqLattice (r : Fin k → ZMod q) {D : ℕ} (hq : 0 < q) (hD : 0 < D) :
    HasIndependentShort (freqLattice r) (freqBox q D) (k + 1) (q : ℝ) := by
  refine ⟨fun i ↦ Pi.single i (q : ℤ), ?_, fun i ↦ ⟨mem_freqLattice.mpr fun j ↦ ?_, fun j ↦ ?_⟩⟩
  · refine Fintype.linearIndependent_iff.mpr fun c hc i ↦ ?_
    have hi := congr_fun hc i
    simp only [Finset.sum_apply, Pi.smul_apply, Pi.single_apply, smul_eq_mul, mul_ite, mul_zero,
      Finset.sum_ite_eq, Finset.mem_univ, if_true, Pi.zero_apply] at hi
    exact (mul_eq_zero.mp hi).resolve_right (Int.natCast_ne_zero.mpr hq.ne')
  · simp only [Pi.single_apply]
    split <;> split <;> simp
  · have hbox : (1 : ℝ) ≤ (freqBox (k := k) q D j : ℝ) := by
      exact_mod_cast freqBox_pos hq hD j
    simp only [Pi.single_apply]
    split
    · rw [Int.cast_natCast, abs_of_nonneg (Nat.cast_nonneg (α := ℝ) q)]
      nlinarith [Nat.cast_nonneg (α := ℝ) q]
    · rw [Int.cast_zero, abs_zero]
      positivity

end FrequencyLattice

/-- A combination of an adapted family whose coefficients are small against the successive minima
stays inside the correspondingly shrunken box. -/
lemma abs_sum_zsmul_le {d : ℕ} {L : Fin d → ℕ} {lam : Fin d → ℝ} {v : Fin d → (Fin d → ℤ)}
    (hv : ∀ i, IsShort L (lam i) (v i)) {n : Fin d → ℤ} {c : ℝ}
    (hn : ∑ i, |(n i : ℝ)| * lam i ≤ c) (j : Fin d) :
    |(((∑ i, n i • v i) j : ℤ) : ℝ)| ≤ c * L j := by
  have hcoord : ((∑ i, n i • v i) j : ℤ) = ∑ i, n i * v i j := by
    simp [Finset.sum_apply]
  rw [hcoord, Int.cast_sum]
  refine (Finset.abs_sum_le_sum_abs _ _).trans ?_
  refine (Finset.sum_le_sum (g := fun i ↦ |(n i : ℝ)| * lam i * L j) fun i _ ↦ ?_).trans ?_
  · rw [Int.cast_mul, abs_mul]
    exact (mul_le_mul_of_nonneg_left (hv i j) (abs_nonneg _)).trans_eq (by ring)
  · rw [← Finset.sum_mul]
    exact mul_le_mul_of_nonneg_right hn (Nat.cast_nonneg _)

/-- A real number is at most twice its floor plus one. This is what makes the symmetric coefficient
range `[-⌊z⌋, ⌊z⌋]` long enough to carry the lattice point count, including when `z < 1` and the
range degenerates to `{0}`. -/
lemma le_two_mul_floor_add_one (z : ℝ) : z ≤ 2 * (⌊z⌋₊ : ℝ) + 1 := by
  rcases le_or_gt z 1 with hle | hlt
  · linarith [Nat.cast_nonneg (α := ℝ) ⌊z⌋₊]
  · linarith [Nat.lt_floor_add_one z]

/-- **Room.** A multiple of `q` that is at most half of a width `m ≤ q` vanishes. Every reduction
modulo `q` performed by the construction below is licensed by this bound. -/
lemma eq_zero_of_dvd_of_two_mul_abs_le {q z m : ℤ} (hq : 0 < q) (hdvd : q ∣ z)
    (hm : 2 * |z| ≤ m) (hmq : m ≤ q) : z = 0 := by
  obtain ⟨c, rfl⟩ := hdvd
  rcases eq_or_ne c 0 with rfl | hc
  · ring
  · rw [abs_mul, abs_of_pos hq] at hm
    nlinarith [Int.one_le_abs hc]

/-- The elements of a progression built with a symmetric coefficient range are the combinations of
its steps with integer coefficients in that range. -/
lemma gapMap_neg_stepsHom_eq {G : Type*} [AddCommGroup G] {d : ℕ} (x : Fin d → G)
    (L len : Fin d → ℕ) (w : (i : Fin d) → Fin (len i)) {n : Fin d → ℤ}
    (hn : ∀ i, n i = ((w i : ℕ) : ℤ) - L i) :
    gapMap (stepsHom x fun i ↦ -(L i : ℤ)) x len w = stepsHom x n := by
  rw [gapMap, stepsHom_apply, stepsHom_apply, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [hn i, sub_zsmul, natCast_zsmul, neg_zsmul]
  abel

/-! ## Symmetric progressions

The progression built below has coefficients in `[-Lᵢ, Lᵢ]`. Packaging that shape once keeps the
dependent coefficient types out of the construction: the two lemmas of this section are the only
place where the parametrization of a `GAP` by `Fin (length i)` is unfolded. -/

section SymmetricGAP

/-- The progression with steps `x` whose `i`-th coefficient ranges over `[-Lᵢ, Lᵢ]`. -/
def symmetricGAP {G : Type*} [DecidableEq G] [AddCommGroup G] {d : ℕ} (x : Fin d → G)
    (L : Fin d → ℕ) : GAP G :=
  GAP.ofData d (stepsHom x fun i ↦ -(L i : ℤ)) x (fun i ↦ 2 * L i + 1) fun _ ↦ Nat.succ_pos _

variable {G : Type*} [DecidableEq G] [AddCommGroup G] {d : ℕ} {x : Fin d → G} {L : Fin d → ℕ}

@[simp] lemma symmetricGAP_dim : (symmetricGAP x L).dim = d := rfl

@[simp] lemma symmetricGAP_length : (symmetricGAP x L).length = fun i ↦ 2 * L i + 1 := rfl

/-- Every element of the symmetric progression is a combination of its steps with coefficients in
`[-Lᵢ, Lᵢ]`. -/
lemma exists_coeff_of_mem_symmetricGAP {y : G} (hy : y ∈ (symmetricGAP x L).carrier) :
    ∃ n : Fin d → ℤ, (∀ i, |n i| ≤ (L i : ℤ)) ∧ y = stepsHom x n := by
  rw [(symmetricGAP x L).carrier_eq] at hy
  obtain ⟨w, -, rfl⟩ := Finset.mem_image.mp hy
  refine ⟨fun i : Fin d ↦ ((w i : ℕ) : ℤ) - L i, fun i ↦ ?_,
    gapMap_neg_stepsHom_eq x L _ w fun _ ↦ rfl⟩
  have hwi := (w i).isLt
  simp only [symmetricGAP_length] at hwi
  dsimp only
  rw [abs_le]
  omega

/-- The symmetric progression is proper as soon as its steps admit no nonzero relation with
coefficients in the doubled range. -/
lemma proper_symmetricGAP
    (h : ∀ n : Fin d → ℤ, (∀ i, |n i| ≤ 2 * (L i : ℤ)) → stepsHom x n = 0 → ∀ i, n i = 0) :
    (symmetricGAP x L).Proper := by
  intro w w' hww'
  have hrel : stepsHom x ((fun i : Fin d ↦ ((w i : ℕ) : ℤ) - L i) -
      fun i : Fin d ↦ ((w' i : ℕ) : ℤ) - L i) = 0 := by
    rw [map_sub, sub_eq_zero]
    exact (gapMap_neg_stepsHom_eq x L _ w fun _ ↦ rfl).symm.trans
      (hww'.trans (gapMap_neg_stepsHom_eq x L _ w' fun _ ↦ rfl))
  have hbound : ∀ i : Fin d, |((fun i : Fin d ↦ ((w i : ℕ) : ℤ) - L i) -
      fun i : Fin d ↦ ((w' i : ℕ) : ℤ) - L i) i| ≤ 2 * (L i : ℤ) := by
    intro i
    have hwi := (w i).isLt
    have hw'i := (w' i).isLt
    simp only [symmetricGAP_length] at hwi hw'i
    simp only [Pi.sub_apply]
    rw [abs_le]
    omega
  funext i
  have := h _ hbound hrel i
  simp only [Pi.sub_apply] at this
  exact Fin.ext (by omega)

end SymmetricGAP

/-! ## The progression -/

/-- **A large proper progression inside a frequency neighborhood.** For frequencies `r₁, …, r_k` of
`ZMod q` and a width `0 < D ≤ q`, there is a proper progression of dimension `k + 1` all of whose
elements `y` satisfy `rⱼ y ≡ aⱼ (mod q)` for integers `|aⱼ| ≤ D`, and whose size is at least
`q ((D + 1) / q) ^ k` up to the dimensional factor `(2 ^ (k + 5) (k + 1)) ^ (k + 1)`.

The parametrization is injective on the whole coefficient box: properness is proved, not assumed.
Primality of `q` is not used. -/
theorem exists_proper_gap_of_freqLattice {q k : ℕ} [NeZero q] (r : Fin k → ZMod q) {D : ℕ}
    (hD : 0 < D) (hDq : D ≤ q) :
    ∃ Q : GAP (ZMod q), Q.Proper ∧ Q.dim = k + 1 ∧
      (∀ y ∈ Q.carrier, ∀ j, ∃ a : ℤ, (a : ZMod q) = r j * y ∧ |a| ≤ (D : ℤ)) ∧
      (q : ℝ) * ((D : ℝ) + 1) ^ k ≤
        (2 : ℝ) ^ ((k + 5) * (k + 1)) * ((k : ℝ) + 1) ^ (k + 1) * (q : ℝ) ^ k *
          Q.carrier.card := by
  have hq : 0 < q := Nat.pos_of_ne_zero (NeZero.ne q)
  have hBpos := freqBox_pos (k := k) (D := D) hq hD
  have hshort := hasIndependentShort_freqLattice r hq hD
  obtain ⟨v, hvindep, hv⟩ := exists_adapted_shortFamily hBpos (Nat.cast_nonneg q) hshort
  set lam : Fin (k + 1) → ℝ :=
    fun i ↦ successiveMinimum (freqLattice r) (freqBox q D) ((i : ℕ) + 1) with hlamdef
  have hlampos : ∀ i, 0 < lam i := by
    intro i
    refine BoxLattice.successiveMinimum_pos (Nat.le_add_left 1 _)
      ⟨(q : ℝ), Nat.cast_nonneg q, hshort.of_le ?_⟩
    have := i.isLt
    omega
  set L : Fin (k + 1) → ℕ := fun i ↦ ⌊1 / (4 * ((k : ℝ) + 1) * lam i)⌋₊ with hLdef
  set len : Fin (k + 1) → ℕ := fun i ↦ 2 * L i + 1 with hlendef
  -- Every coefficient vector of the doubled box gives a lattice vector inside half the box.
  have hhalf : ∀ n : Fin (k + 1) → ℤ, (∀ i, |n i| ≤ 2 * L i) →
      (∑ i, n i • v i) ∈ freqLattice r ∧
        ∀ j, 2 * |(∑ i, n i • v i) j| ≤ (freqBox q D j : ℤ) := by
    intro n hn
    refine ⟨AddSubgroup.sum_mem _ fun i _ ↦ AddSubgroup.zsmul_mem _ (hv i).1 _, fun j ↦ ?_⟩
    have hsum : ∑ i, |(n i : ℝ)| * lam i ≤ 1 / 2 := by
      refine (Finset.sum_le_sum
        (g := fun _ : Fin (k + 1) ↦ 1 / (2 * ((k : ℝ) + 1))) fun i _ ↦ ?_).trans ?_
      · have hlami := hlampos i
        have hni : |(n i : ℝ)| ≤ 2 * L i := by
          have := (Int.cast_le (R := ℝ)).mpr (hn i)
          push_cast at this
          exact this
        have hfloor : (L i : ℝ) ≤ 1 / (4 * ((k : ℝ) + 1) * lam i) :=
          Nat.floor_le (by positivity)
        rw [le_div_iff₀ (by positivity)] at hfloor
        rw [le_div_iff₀ (by positivity)]
        nlinarith [mul_le_mul_of_nonneg_right hni
          (by positivity : (0 : ℝ) ≤ lam i * (2 * ((k : ℝ) + 1)))]
      · rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul, mul_one_div,
          div_le_div_iff₀ (by positivity) (by norm_num)]
        push_cast
        ring_nf
        linarith
    have hbox := abs_sum_zsmul_le (fun i ↦ (hv i).2) hsum j
    rw [← Int.cast_le (R := ℝ)]
    push_cast
    linarith
  -- The progression generated by the first coordinates of the adapted family.
  set x : Fin (k + 1) → ZMod q := fun i ↦ ((v i 0 : ℤ) : ZMod q) with hxdef
  have hstepsHom : ∀ n : Fin (k + 1) → ℤ,
      stepsHom x n = (((∑ i, n i • v i) 0 : ℤ) : ZMod q) := by
    intro n
    have hcoord : ((∑ i, n i • v i) 0 : ℤ) = ∑ i, n i * v i 0 := by
      simp [Finset.sum_apply]
    rw [stepsHom_apply, hcoord, Int.cast_sum]
    exact Finset.sum_congr rfl fun i _ ↦ by rw [Int.cast_mul, zsmul_eq_mul, hxdef]
  have hqz : (0 : ℤ) < q := by exact_mod_cast hq
  -- A relation of the steps with coefficients in the doubled range is trivial: its lattice vector
  -- lies in half the box, so no coordinate can wrap around `q`.
  have hrelation : ∀ n : Fin (k + 1) → ℤ, (∀ i, |n i| ≤ 2 * (L i : ℤ)) →
      stepsHom x n = 0 → ∀ i, n i = 0 := by
    intro n hn hzero i
    obtain ⟨hmem, hbox⟩ := hhalf n hn
    have hfirst : (∑ i, n i • v i) 0 = 0 := by
      refine eq_zero_of_dvd_of_two_mul_abs_le hqz ?_ (hbox 0) (by simp)
      rw [← ZMod.intCast_zmod_eq_zero_iff_dvd, ← hstepsHom, hzero]
    refine Fintype.linearIndependent_iff.mp hvindep n ?_ i
    funext j
    refine Fin.cases hfirst (fun j ↦ ?_) j
    refine eq_zero_of_dvd_of_two_mul_abs_le hqz ?_ (hbox j.succ) ?_
    · rw [← ZMod.intCast_zmod_eq_zero_iff_dvd, mem_freqLattice.mp hmem j, hfirst]
      simp
    · rw [freqBox_succ]
      exact_mod_cast hDq
  refine ⟨symmetricGAP x L, proper_symmetricGAP hrelation, rfl, ?_, ?_⟩
  · -- The Bohr certificate.
    intro y hy j
    obtain ⟨n, hn, rfl⟩ := exists_coeff_of_mem_symmetricGAP hy
    obtain ⟨hmem, hbox⟩ := hhalf n fun i ↦ (hn i).trans (by omega)
    refine ⟨(∑ i, n i • v i) j.succ, ?_, ?_⟩
    · rw [mem_freqLattice.mp hmem j, ← hstepsHom]
    · have := hbox j.succ
      rw [freqBox_succ] at this
      omega
  · -- The size, from the two lattice point counts.
    have hfin : (BoxLattice.latticeBoxPoints (freqLattice r) (freqBox q D)).Finite :=
      Set.Finite.subset (intBox (freqBox q D)).finite_toSet fun z hz ↦ mem_intBox.mpr hz.2
    have hlow : ∏ i, (freqBox (k := k) q D i + 1) ≤
        (BoxLattice.latticeBoxPoints (freqLattice r) (freqBox q D)).ncard * q ^ k := by
      by_contra hcon
      push Not at hcon
      obtain ⟨F, hFcard, hF⟩ := exists_card_lt_forall_mem_ker_of_mul_card_lt (freqHom r)
        (s := (Finset.univ : Finset (Fin k → ZMod q))) (fun _ _ ↦ Finset.mem_univ _)
        (n := (BoxLattice.latticeBoxPoints (freqLattice r) (freqBox q D)).ncard)
        (by simpa [ZMod.card] using hcon)
      refine absurd hFcard (not_lt.mpr ?_)
      rw [← Set.ncard_coe_finset F]
      exact Set.ncard_le_ncard (fun z hz ↦ ⟨(hF z hz).1, (hF z hz).2⟩) hfin
    have hupper : ((BoxLattice.latticeBoxPoints (freqLattice r) (freqBox q D)).ncard : ℝ) ≤
        ((2 : ℝ) ^ (k + 5) * ((k : ℝ) + 1)) ^ (k + 1) * ∏ i, (len i : ℝ) := by
      have hconst : ((2 : ℝ) ^ (k + 5) * ((k : ℝ) + 1)) ^ (k + 1) * ∏ i, (len i : ℝ) =
          ∏ i : Fin (k + 1), ((2 : ℝ) ^ (k + 5) * ((k : ℝ) + 1) * len i) := by
        rw [Finset.prod_mul_distrib, Finset.prod_const, Finset.card_univ, Fintype.card_fin]
      refine (BoxLattice.ncard_latticeBoxPoints_le _ hBpos).trans ?_
      rw [hconst]
      refine Finset.prod_le_prod (fun i _ ↦ ?_) fun i _ ↦ ?_
      · have := hlampos i
        positivity
      · have hlami := hlampos i
        have hlen1 : (1 : ℝ) ≤ (len i : ℝ) := by
          rw [hlendef]
          push_cast
          linarith [Nat.cast_nonneg (α := ℝ) (L i)]
        have hinv : 1 ≤ (len i : ℝ) * (4 * ((k : ℝ) + 1) * lam i) := by
          rw [← div_le_iff₀ (by positivity), hlendef, hLdef]
          push_cast
          exact le_two_mul_floor_add_one _
        have hpow : (0 : ℝ) < 2 ^ (k + 1 + 1) := by positivity
        have hdiv : (2 : ℝ) ^ (k + 1 + 1) / lam i ≤
            2 ^ (k + 1 + 1) * (4 * (((k : ℝ) + 1) * len i)) := by
          rw [div_le_iff₀ hlami]
          nlinarith [mul_le_mul_of_nonneg_left hinv hpow.le]
        have hbig : (1 : ℝ) ≤ 2 ^ (k + 1 + 1) * (4 * (((k : ℝ) + 1) * len i)) := by
          have hklen : (1 : ℝ) ≤ 4 * (((k : ℝ) + 1) * len i) := by
            nlinarith [Nat.cast_nonneg (α := ℝ) k]
          nlinarith [one_le_pow₀ (by norm_num : (1 : ℝ) ≤ 2) (n := k + 1 + 1)]
        rw [show (2 : ℝ) ^ (k + 5) = 2 ^ (k + 1 + 1) * 8 by
          rw [show k + 5 = k + 1 + 1 + 3 by ring, pow_add]
          norm_num]
        linarith
    have hcard : ((symmetricGAP x L).carrier.card : ℝ) = ∏ i, (len i : ℝ) := by
      rw [GAP.card_eq_prod_length _ (proper_symmetricGAP hrelation), Nat.cast_prod]
      rfl
    have hboxprod : ((∏ i, (freqBox (k := k) q D i + 1) : ℕ) : ℝ) =
        ((q : ℝ) + 1) * ((D : ℝ) + 1) ^ k := by
      rw [Nat.cast_prod, Fin.prod_univ_succ]
      simp
    have hlowreal := (Nat.cast_le (α := ℝ)).mpr hlow
    rw [hboxprod, Nat.cast_mul, Nat.cast_pow] at hlowreal
    rw [mul_pow, ← pow_mul] at hupper
    rw [hcard]
    linarith [pow_nonneg (by positivity : (0 : ℝ) ≤ (D : ℝ) + 1) k,
      hlowreal.trans (mul_le_mul_of_nonneg_right hupper (by positivity : (0 : ℝ) ≤ (q : ℝ) ^ k))]

/-- **A large proper progression inside a chord neighborhood.** The chord neighborhood of width `ε`
of a finite set `Δ` of characters of `ZMod q` contains a proper progression of dimension
`|Δ| + 1` and density at least `(ε / 2 π) ^ |Δ|`, up to the dimensional factor
`(2 ^ (|Δ| + 5) (|Δ| + 1)) ^ (|Δ| + 1)`.

The hypothesis `2 π ≤ ε q` is what makes the neighborhood wider than one step of `ZMod q`; without
it the neighborhood can be `{0}`. -/
theorem exists_proper_gap_chordSet {q : ℕ} [NeZero q] (Δ : Finset (AddChar (ZMod q) ℂ)) {ε : ℝ}
    (hεq : 2 * Real.pi ≤ ε * q) (hε : ε ≤ 1) :
    ∃ Q : GAP (ZMod q), Q.Proper ∧ Q.dim = Δ.card + 1 ∧
      (Q.carrier : Set (ZMod q)) ⊆ {x | ∀ ψ ∈ Δ, ‖1 - ψ x‖ ≤ ε} ∧
      (q : ℝ) * (ε / (2 * Real.pi)) ^ Δ.card ≤
        (2 : ℝ) ^ ((Δ.card + 5) * (Δ.card + 1)) * ((Δ.card : ℝ) + 1) ^ (Δ.card + 1) *
          Q.carrier.card := by
  have hq : (0 : ℝ) < q := by exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne q)
  have hpi := Real.pi_gt_three
  have hεpos : 0 < ε := by nlinarith
  choose r hr using fun i : Fin Δ.card ↦
    exists_frequency_chord_le ((Δ.equivFin.symm i : Δ) : AddChar (ZMod q) ℂ)
  have hfloor : (⌊ε * q / (2 * Real.pi)⌋₊ : ℝ) ≤ ε * q / (2 * Real.pi) :=
    Nat.floor_le (by positivity)
  have hDpos : 0 < ⌊ε * q / (2 * Real.pi)⌋₊ := by
    rw [Nat.floor_pos, le_div_iff₀ (by positivity)]
    linarith
  have hDq : ⌊ε * q / (2 * Real.pi)⌋₊ ≤ q := by
    refine (Nat.floor_le_floor (b := (q : ℝ)) ?_).trans (le_of_eq (Nat.floor_natCast (R := ℝ) q))
    rw [div_le_iff₀ (by positivity)]
    nlinarith [mul_le_mul_of_nonneg_right hε hq.le]
  obtain ⟨Q, hproper, hdim, hcert, hsize⟩ :=
    exists_proper_gap_of_freqLattice r hDpos hDq
  refine ⟨Q, hproper, hdim, fun y hy ψ hψ ↦ ?_, ?_⟩
  · obtain ⟨a, ha, habs⟩ := hcert y hy (Δ.equivFin ⟨ψ, hψ⟩)
    have hchord := hr (Δ.equivFin ⟨ψ, hψ⟩) y a ha
    simp only [Equiv.symm_apply_apply] at hchord
    refine hchord.trans ?_
    rw [div_le_iff₀ hq]
    have hcast : |(a : ℝ)| ≤ (⌊ε * q / (2 * Real.pi)⌋₊ : ℝ) := by
      have := (Int.cast_le (R := ℝ)).mpr habs
      rwa [Int.cast_abs, Int.cast_natCast] at this
    rw [le_div_iff₀ (by positivity)] at hfloor
    nlinarith [abs_nonneg (a : ℝ)]
  · refine le_of_mul_le_mul_right ?_ (pow_pos hq Δ.card)
    have hgrow : (q : ℝ) * ((ε / (2 * Real.pi)) ^ Δ.card * (q : ℝ) ^ Δ.card) ≤
        (q : ℝ) * ((⌊ε * q / (2 * Real.pi)⌋₊ : ℝ) + 1) ^ Δ.card := by
      rw [← mul_pow]
      refine mul_le_mul_of_nonneg_left (pow_le_pow_left₀ (by positivity) ?_ _) hq.le
      rw [show ε / (2 * Real.pi) * (q : ℝ) = ε * q / (2 * Real.pi) by ring]
      exact (Nat.lt_floor_add_one _).le
    linarith [hgrow.trans hsize]

end

end DenseSetsWithoutLargeSumsets
