/-
Copyright (c) 2026 Gabriel Dahia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gabriel Dahia
-/
import Mathlib.Algebra.Module.ZLattice.Basic
import DenseSetsWithoutLargeSumsets.Combinatorics.Additive.Chang.ConvexProgression

/-! # Lattices in coordinate subspaces

This file sets up the lattice `H ∩ ℤ^d` used in Appendix A. The remaining task is to show that it
spans `H` when `H` is generated by integral vectors and then transport a chosen lattice basis to a
full-dimensional rational Freiman model.
-/

namespace DenseSetsWithoutLargeSumsets

noncomputable section

/-- The standard integer lattice in `ℝ^d`. -/
def standardIntegerLattice (d : ℕ) : Submodule ℤ (Fin d → ℝ) :=
  Submodule.span ℤ (Set.range (Pi.basisFun ℝ (Fin d)))

instance standardIntegerLattice_discrete (d : ℕ) :
    DiscreteTopology (standardIntegerLattice d) := by
  exact ZSpan.discreteTopology_pi_basisFun

lemma standardIntegerLattice_span_top (d : ℕ) :
    Submodule.span ℝ (standardIntegerLattice d : Set (Fin d → ℝ)) = ⊤ := by
  simp [standardIntegerLattice]

lemma intVectorToReal_mem_standardIntegerLattice {d : ℕ} (v : Fin d → ℤ) :
    intVectorToReal v ∈ standardIntegerLattice d := by
  rw [standardIntegerLattice]
  suffices intVectorToReal v = ∑ i, v i • Pi.basisFun ℝ (Fin d) i by
    rw [this]
    apply Submodule.sum_mem
    intro i hi
    exact Submodule.smul_mem _ (v i)
      (Submodule.subset_span (Set.mem_range_self i))
  simpa [intVectorToReal, Int.cast_smul_eq_zsmul] using
    ((Pi.basisFun ℝ (Fin d)).sum_repr (intVectorToReal v)).symm

/-- The integer lattice in a real coordinate subspace `H`, represented as a submodule of `H`. -/
def subspaceIntegerLattice {d : ℕ} (H : Submodule ℝ (Fin d → ℝ)) : Submodule ℤ H :=
  ZLattice.comap ℝ (standardIntegerLattice d) H.subtype

/-- The real subspace generated by a finite set of integer vectors. -/
def integerGeneratedSubspace {d : ℕ} (S : Finset (Fin d → ℤ)) :
    Submodule ℝ (Fin d → ℝ) :=
  Submodule.span ℝ (intVectorToReal '' (S : Set (Fin d → ℤ)))

lemma subspaceIntegerLattice_discrete {d : ℕ} (H : Submodule ℝ (Fin d → ℝ)) :
    DiscreteTopology (subspaceIntegerLattice H) := by
  exact ZLattice.comap_discreteTopology ℝ (standardIntegerLattice d)
    H.subtype.continuous_of_finiteDimensional H.subtype_injective

lemma subspaceIntegerLattice_isZLattice {d : ℕ} (H : Submodule ℝ (Fin d → ℝ))
    (hspan : Submodule.span ℝ (subspaceIntegerLattice H : Set H) = ⊤) :
    @IsZLattice ℝ _ H _ _ (subspaceIntegerLattice H)
      (subspaceIntegerLattice_discrete H) := by
  letI : DiscreteTopology (subspaceIntegerLattice H) := subspaceIntegerLattice_discrete H
  exact ⟨hspan⟩

lemma integerGeneratedSubspace_lattice_span_top {d : ℕ} (S : Finset (Fin d → ℤ)) :
    Submodule.span ℝ
      (subspaceIntegerLattice (integerGeneratedSubspace S) :
        Set (integerGeneratedSubspace S)) = ⊤ := by
  let H := integerGeneratedSubspace S
  let L := subspaceIntegerLattice H
  apply (Submodule.map_injective_of_injective H.subtype_injective)
  rw [Submodule.map_top, Submodule.range_subtype]
  rw [Submodule.map_span]
  apply le_antisymm
  · exact Submodule.span_le.mpr fun x hx ↦ by
      obtain ⟨y, hy, rfl⟩ := hx
      exact y.property
  · change Submodule.span ℝ (intVectorToReal '' (S : Set (Fin d → ℤ))) ≤ _
    apply Submodule.span_le.mpr
    intro x hx
    obtain ⟨v, hvS, rfl⟩ := hx
    have hvH : intVectorToReal v ∈ H := by
      apply Submodule.subset_span
      exact ⟨v, hvS, rfl⟩
    let y : H := ⟨intVectorToReal v, hvH⟩
    have hyL : y ∈ L := by
      exact intVectorToReal_mem_standardIntegerLattice v
    apply Submodule.subset_span
    exact ⟨y, hyL, rfl⟩

instance integerGeneratedSubspace_lattice_discrete {d : ℕ} (S : Finset (Fin d → ℤ)) :
    DiscreteTopology (subspaceIntegerLattice (integerGeneratedSubspace S)) :=
  subspaceIntegerLattice_discrete _

instance integerGeneratedSubspace_isZLattice {d : ℕ} (S : Finset (Fin d → ℤ)) :
    IsZLattice ℝ (subspaceIntegerLattice (integerGeneratedSubspace S)) :=
  ⟨integerGeneratedSubspace_lattice_span_top S⟩

lemma integerGeneratedSubspace_lattice_rank {d : ℕ} (S : Finset (Fin d → ℤ)) :
    Module.finrank ℤ (subspaceIntegerLattice (integerGeneratedSubspace S)) =
      Module.finrank ℝ (integerGeneratedSubspace S) := by
  exact ZLattice.rank ℝ _

/-- A `Fin r`-indexed basis of the saturated lattice, where `r = dim H`. -/
noncomputable def integerGeneratedLatticeBasis {d : ℕ} (S : Finset (Fin d → ℤ)) :
    Module.Basis (Fin (Module.finrank ℝ (integerGeneratedSubspace S))) ℤ
      (subspaceIntegerLattice (integerGeneratedSubspace S)) :=
  (Module.Free.chooseBasis ℤ (subspaceIntegerLattice (integerGeneratedSubspace S))).reindex
    (Fintype.equivFinOfCardEq (by
      rw [← Module.finrank_eq_card_chooseBasisIndex,
        integerGeneratedSubspace_lattice_rank]))

/-- The associated real basis of the integral-coordinate subspace. -/
noncomputable def integerGeneratedRealBasis {d : ℕ} (S : Finset (Fin d → ℤ)) :
    Module.Basis (Fin (Module.finrank ℝ (integerGeneratedSubspace S))) ℝ
      (integerGeneratedSubspace S) :=
  (integerGeneratedLatticeBasis S).ofZLatticeBasis ℝ
    (subspaceIntegerLattice (integerGeneratedSubspace S))

/-- Real coordinates on the subspace, indexed by `Fin (dim H)`. -/
noncomputable def integerGeneratedCoordinateEquiv {d : ℕ} (S : Finset (Fin d → ℤ)) :
    integerGeneratedSubspace S ≃ₗ[ℝ]
      (Fin (Module.finrank ℝ (integerGeneratedSubspace S)) → ℝ) :=
  (integerGeneratedRealBasis S).equivFun

/-- Integer coordinates of a point of the saturated lattice. -/
noncomputable def integerGeneratedLatticeCoordinates {d : ℕ}
    (S : Finset (Fin d → ℤ))
    (x : subspaceIntegerLattice (integerGeneratedSubspace S)) :
    Fin (Module.finrank ℝ (integerGeneratedSubspace S)) → ℤ :=
  fun i ↦ (integerGeneratedLatticeBasis S).repr x i

lemma integerGeneratedCoordinateEquiv_apply_lattice {d : ℕ}
    (S : Finset (Fin d → ℤ))
    (x : subspaceIntegerLattice (integerGeneratedSubspace S))
    (i : Fin (Module.finrank ℝ (integerGeneratedSubspace S))) :
    integerGeneratedCoordinateEquiv S x i =
      (integerGeneratedLatticeCoordinates S x i : ℝ) := by
  unfold integerGeneratedCoordinateEquiv integerGeneratedRealBasis
    integerGeneratedLatticeCoordinates
  exact Module.Basis.ofZLatticeBasis_repr_apply ℝ
    (subspaceIntegerLattice (integerGeneratedSubspace S))
    (integerGeneratedLatticeBasis S) x i

/-- The lattice coordinate map as an additive homomorphism into `ℤ^r`. -/
noncomputable def integerGeneratedLatticeCoordHom {d : ℕ} (S : Finset (Fin d → ℤ)) :
    subspaceIntegerLattice (integerGeneratedSubspace S) →+
      (Fin (Module.finrank ℝ (integerGeneratedSubspace S)) → ℤ) :=
  let e := (integerGeneratedLatticeBasis S).repr.trans
    (Finsupp.linearEquivFunOnFinite ℤ ℤ _)
  e.toAddEquiv.toAddMonoidHom

lemma integerGeneratedLatticeCoordHom_apply {d : ℕ} (S : Finset (Fin d → ℤ))
    (x : subspaceIntegerLattice (integerGeneratedSubspace S))
    (i : Fin (Module.finrank ℝ (integerGeneratedSubspace S))) :
    integerGeneratedLatticeCoordHom S x i =
      integerGeneratedLatticeCoordinates S x i := by
  rfl

/-- Pointwise rational cast `ℤ^r →+ ℚ^r`. -/
def ratCoordHom {r : ℕ} : (Fin r → ℤ) →+ (Fin r → ℚ) where
  toFun v := fun i ↦ (v i : ℚ)
  map_zero' := by ext i; simp
  map_add' := by intro a b; ext i; simp [Pi.add_apply, Int.cast_add]

lemma ratCoordHom_injective {r : ℕ} :
    Function.Injective (ratCoordHom (r := r)) := by
  intro a b h
  funext i
  have hi := congr_fun h i
  change (a i : ℚ) = (b i : ℚ) at hi
  exact_mod_cast hi

lemma integerGeneratedLatticeCoordHom_injective {d : ℕ} (S : Finset (Fin d → ℤ)) :
    Function.Injective (integerGeneratedLatticeCoordHom S) := by
  unfold integerGeneratedLatticeCoordHom
  exact LinearEquiv.injective _

/-! ## Integral representatives of lattice points -/

lemma exists_intVectorToReal_of_mem_standardIntegerLattice {d : ℕ} {x : Fin d → ℝ}
    (hx : x ∈ standardIntegerLattice d) : ∃ v : Fin d → ℤ, intVectorToReal v = x := by
  rw [standardIntegerLattice, (Pi.basisFun ℝ (Fin d)).mem_span_iff_repr_mem ℤ] at hx
  choose v hv using hx
  refine ⟨v, funext fun i ↦ ?_⟩
  simpa [intVectorToReal] using hv i

lemma mem_standardIntegerLattice_of_mem_subspaceIntegerLattice {d : ℕ}
    {H : Submodule ℝ (Fin d → ℝ)} {x : H} (hx : x ∈ subspaceIntegerLattice H) :
    (x : Fin d → ℝ) ∈ standardIntegerLattice d := hx

/-- An integral representative of the `i`-th vector of the saturated lattice basis. -/
noncomputable def latticeBasisIntVector {d : ℕ} (S : Finset (Fin d → ℤ))
    (i : Fin (Module.finrank ℝ (integerGeneratedSubspace S))) : Fin d → ℤ :=
  Classical.choose (exists_intVectorToReal_of_mem_standardIntegerLattice
    (mem_standardIntegerLattice_of_mem_subspaceIntegerLattice
      (integerGeneratedLatticeBasis S i).2))

lemma intVectorToReal_latticeBasisIntVector {d : ℕ} (S : Finset (Fin d → ℤ))
    (i : Fin (Module.finrank ℝ (integerGeneratedSubspace S))) :
    intVectorToReal (latticeBasisIntVector S i) =
      ((integerGeneratedLatticeBasis S i : integerGeneratedSubspace S) : Fin d → ℝ) :=
  Classical.choose_spec (exists_intVectorToReal_of_mem_standardIntegerLattice
    (mem_standardIntegerLattice_of_mem_subspaceIntegerLattice
      (integerGeneratedLatticeBasis S i).2))

lemma intVectorToReal_zsmul {d : ℕ} (n : ℤ) (v : Fin d → ℤ) :
    intVectorToReal (n • v) = n • intVectorToReal v := by
  ext i
  simp [intVectorToReal, Pi.smul_apply, zsmul_eq_mul]

lemma intVectorToReal_sum {ι : Type*} {d : ℕ} (s : Finset ι) (f : ι → Fin d → ℤ) :
    intVectorToReal (∑ i ∈ s, f i) = ∑ i ∈ s, intVectorToReal (f i) := by
  classical
  induction s using Finset.induction with
  | empty => simp
  | insert a s ha ih => rw [Finset.sum_insert ha, Finset.sum_insert ha, intVectorToReal_add, ih]

end

end DenseSetsWithoutLargeSumsets
