/-
Copyright (c) 2026 Gabriel Dahia. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gabriel Dahia
-/
import DenseSetsWithoutLargeSumsets.AdditiveCombinatorics.Chang.Model

/-! # Effective lattice coordinates for box reboxing

This file transports a finite set `D ⊆ ℤ^d` to the saturated lattice in its real span, whose rank
is the effective dimension of `D`. The coordinate and reconstruction maps are reusable in the
specialized projection and slice reboxing arguments.
-/

namespace DenseSetsWithoutLargeSumsets

noncomputable section

variable {d : ℕ} (D : Finset (Fin d → ℤ))

open Classical in
/-- Integer coordinates in the saturated lattice generated by `D`, extended by zero away from its
real span. -/
noncomputable def effectiveLatticeMap (y : Fin d → ℤ) :
    Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ :=
  if hy : y ∈ latticeDomain D then
    integerGeneratedLatticeCoordHom D (latticeEmbed D ⟨y, hy⟩)
  else 0

lemma effectiveLatticeMap_eq_on {y : Fin d → ℤ} (hy : y ∈ latticeDomain D) :
    effectiveLatticeMap D y =
      integerGeneratedLatticeCoordHom D (latticeEmbed D ⟨y, hy⟩) := by
  unfold effectiveLatticeMap
  rw [dif_pos hy]

lemma effectiveLatticeMap_injective_on :
    Set.InjOn (effectiveLatticeMap D) (latticeDomain D) := by
  intro a ha b hb h
  rw [effectiveLatticeMap_eq_on D ha, effectiveLatticeMap_eq_on D hb] at h
  exact congr_arg Subtype.val
    (latticeEmbed_injective D (integerGeneratedLatticeCoordHom_injective D h))

lemma intVectorToReal_effectiveLatticeMap {y : Fin d → ℤ} (hy : y ∈ latticeDomain D) :
    intVectorToReal (effectiveLatticeMap D y) =
      integerGeneratedCoordinateEquiv D (latticeEmbed D ⟨y, hy⟩) := by
  rw [effectiveLatticeMap_eq_on D hy]
  ext i
  rw [intVectorToReal, integerGeneratedCoordinateEquiv_apply_lattice,
    integerGeneratedLatticeCoordHom_apply]

/-- The saturated-lattice point with prescribed effective coordinates. -/
noncomputable def effectiveLatticePoint
    (v : Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ) :
    subspaceIntegerLattice (integerGeneratedSubspace D) :=
  ∑ i, v i • integerGeneratedLatticeBasis D i

/-- The ambient integer vector with prescribed effective coordinates. -/
noncomputable def effectiveLatticeVector
    (v : Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ) : Fin d → ℤ :=
  ∑ i, v i • latticeBasisIntVector D i

lemma intVectorToReal_effectiveLatticeVector
    (v : Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ) :
    intVectorToReal (effectiveLatticeVector D v) =
      ((effectiveLatticePoint D v : integerGeneratedSubspace D) : Fin d → ℝ) := by
  rw [effectiveLatticeVector, intVectorToReal_sum, effectiveLatticePoint]
  push_cast
  exact Finset.sum_congr rfl fun i _ ↦ by
    rw [intVectorToReal_zsmul, intVectorToReal_latticeBasisIntVector]

lemma effectiveLatticeVector_mem_latticeDomain
    (v : Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ) :
    effectiveLatticeVector D v ∈ latticeDomain D := by
  change intVectorToReal (effectiveLatticeVector D v) ∈ integerGeneratedSubspace D
  rw [intVectorToReal_effectiveLatticeVector]
  exact (effectiveLatticePoint D v : integerGeneratedSubspace D).2

lemma latticeEmbed_effectiveLatticeVector
    (v : Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ) :
    latticeEmbed D
        ⟨effectiveLatticeVector D v, effectiveLatticeVector_mem_latticeDomain D v⟩ =
      effectiveLatticePoint D v := by
  refine Subtype.ext (Subtype.ext ?_)
  exact intVectorToReal_effectiveLatticeVector D v

lemma effectiveLatticeMap_effectiveLatticeVector
    (v : Fin (Module.finrank ℝ (integerGeneratedSubspace D)) → ℤ) :
    effectiveLatticeMap D (effectiveLatticeVector D v) = v := by
  rw [effectiveLatticeMap_eq_on D (effectiveLatticeVector_mem_latticeDomain D v),
    latticeEmbed_effectiveLatticeVector]
  funext i
  rw [integerGeneratedLatticeCoordHom_apply]
  unfold integerGeneratedLatticeCoordinates effectiveLatticePoint
  rw [(integerGeneratedLatticeBasis D).repr_sum_self]

lemma effectiveLatticeVector_effectiveLatticeMap {y : Fin d → ℤ}
    (hy : y ∈ latticeDomain D) :
    effectiveLatticeVector D (effectiveLatticeMap D y) = y := by
  refine effectiveLatticeMap_injective_on D
    (effectiveLatticeVector_mem_latticeDomain D _) hy ?_
  rw [effectiveLatticeMap_effectiveLatticeVector]

/-- The effective rank of a finite set of integer vectors. -/
abbrev effectiveRank : ℕ := Module.finrank ℝ (integerGeneratedSubspace D)

/-- The set `D` in saturated-lattice coordinates. -/
noncomputable def effectiveLatticeCoords : Finset (Fin (effectiveRank D) → ℤ) :=
  D.image (effectiveLatticeMap D)

lemma mem_effectiveLatticeCoords {v : Fin (effectiveRank D) → ℤ} :
    v ∈ effectiveLatticeCoords D ↔ effectiveLatticeVector D v ∈ D := by
  constructor
  · intro hv
    obtain ⟨y, hyD, rfl⟩ := Finset.mem_image.mp hv
    rw [effectiveLatticeVector_effectiveLatticeMap D
      (mem_latticeDomain_of_mem D hyD)]
    exact hyD
  · intro hv
    rw [← effectiveLatticeMap_effectiveLatticeVector D v]
    exact Finset.mem_image_of_mem _ hv

lemma card_effectiveLatticeCoords :
    (effectiveLatticeCoords D).card = D.card := by
  rw [effectiveLatticeCoords, Finset.card_image_of_injOn]
  intro a ha b hb h
  exact effectiveLatticeMap_injective_on D
    (mem_latticeDomain_of_mem D ha) (mem_latticeDomain_of_mem D hb) h

/-- A nonempty symmetric convex progression contains the origin. -/
lemma zero_mem_of_nonempty_isSymmetricConvexProgression
    (hD : D.Nonempty) {r : ℕ} (hconvex : IsSymmetricConvexProgression (r := r) D) :
    (0 : Fin d → ℤ) ∈ D := by
  obtain ⟨K, hKconv, hKsymm, hDK, -⟩ := hconvex
  obtain ⟨v, hvD⟩ := hD
  have hvK := (hDK v).mp hvD
  refine (hDK 0).mpr ?_
  rw [intVectorToReal_zero]
  have hmid := hKconv hvK ((hKsymm _).mp hvK)
    (show (0 : ℝ) ≤ 2⁻¹ by positivity) (show (0 : ℝ) ≤ 2⁻¹ by positivity)
    (by norm_num : (2 : ℝ)⁻¹ + 2⁻¹ = 1)
  simpa only [smul_neg, add_neg_cancel] using hmid

/-- When the origin belongs to `D`, its affine dimension is the rank of its real linear span. -/
lemma effectiveRank_eq_finsetAffineDim (h0 : (0 : Fin d → ℤ) ∈ D) :
    effectiveRank D = finsetAffineDim (D.image intVectorToReal) := by
  unfold effectiveRank integerGeneratedSubspace finsetAffineDim
  rw [direction_affineSpan,
    vectorSpan_eq_span_vsub_set_right ℝ
      (Finset.mem_coe.mpr (Finset.mem_image_of_mem intVectorToReal h0))]
  have hsets :
      intVectorToReal '' (D : Set (Fin d → ℤ)) =
        (fun x ↦ x -ᵥ intVectorToReal 0) ''
          ((D.image intVectorToReal : Finset (Fin d → ℝ)) : Set _) := by
    ext x
    simp [vsub_eq_sub]
  rw [hsets]

/-- The effective rank is bounded by the advertised affine dimension. -/
lemma effectiveRank_le_of_isSymmetricConvexProgression
    (hD : D.Nonempty) {r : ℕ} (hconvex : IsSymmetricConvexProgression (r := r) D) :
    effectiveRank D ≤ r := by
  rw [effectiveRank_eq_finsetAffineDim D
    (zero_mem_of_nonempty_isSymmetricConvexProgression D hD hconvex)]
  exact hconvex.choose_spec.2.2.2

/-- A body in the span of `D`, expressed in saturated-lattice coordinates. -/
def effectiveLatticeBody (K : Set (Fin d → ℝ)) : Set (Fin (effectiveRank D) → ℝ) :=
  integerGeneratedCoordinateEquiv D ''
    {p : integerGeneratedSubspace D | (p : Fin d → ℝ) ∈ K}

lemma convex_effectiveLatticeBody {K : Set (Fin d → ℝ)} (hK : Convex ℝ K) :
    Convex ℝ (effectiveLatticeBody D K) := by
  refine Convex.linear_image ?_ (integerGeneratedCoordinateEquiv D).toLinearMap
  intro x hx y hy a b ha hb hab
  exact hK hx hy ha hb hab

lemma neg_mem_effectiveLatticeBody {K : Set (Fin d → ℝ)}
    (hsymm : ∀ x, x ∈ K ↔ -x ∈ K) {x : Fin (effectiveRank D) → ℝ}
    (hx : x ∈ effectiveLatticeBody D K) :
    -x ∈ effectiveLatticeBody D K := by
  obtain ⟨p, hp, rfl⟩ := hx
  exact ⟨-p, (hsymm _).mp hp, map_neg _ p⟩

lemma mem_effectiveLatticeCoords_iff {K : Set (Fin d → ℝ)}
    (hDK : ∀ v : Fin d → ℤ, v ∈ D ↔ intVectorToReal v ∈ K)
    {v : Fin (effectiveRank D) → ℤ} :
    v ∈ effectiveLatticeCoords D ↔ intVectorToReal v ∈ effectiveLatticeBody D K := by
  rw [mem_effectiveLatticeCoords, hDK]
  constructor
  · intro hv
    refine ⟨effectiveLatticePoint D v, ?_, ?_⟩
    · change
        ((effectiveLatticePoint D v : integerGeneratedSubspace D) : Fin d → ℝ) ∈ K
      rw [← intVectorToReal_effectiveLatticeVector]
      exact hv
    · rw [← latticeEmbed_effectiveLatticeVector D v,
        ← intVectorToReal_effectiveLatticeMap D
          (effectiveLatticeVector_mem_latticeDomain D v),
        effectiveLatticeMap_effectiveLatticeVector]
  · rintro ⟨p, hp, hep⟩
    have hcoord :
        integerGeneratedCoordinateEquiv D (effectiveLatticePoint D v) =
          intVectorToReal v := by
      rw [← latticeEmbed_effectiveLatticeVector D v,
        ← intVectorToReal_effectiveLatticeMap D
          (effectiveLatticeVector_mem_latticeDomain D v),
        effectiveLatticeMap_effectiveLatticeVector]
    rw [intVectorToReal_effectiveLatticeVector D v,
      (integerGeneratedCoordinateEquiv D).injective (hcoord.trans hep.symm)]
    exact hp

private lemma finsetAffineDim_le_ambient {s : ℕ} (T : Finset (Fin s → ℝ)) :
    finsetAffineDim T ≤ s := by
  unfold finsetAffineDim
  simpa using Submodule.finrank_le (affineSpan ℝ (T : Set (Fin s → ℝ))).direction

lemma finsetAffineDim_le_effectiveRank :
    finsetAffineDim ((effectiveLatticeCoords D).image intVectorToReal) ≤ effectiveRank D := by
  exact finsetAffineDim_le_ambient _

/-- The real casts of the effective lattice coordinates span their full coordinate space. -/
lemma span_intVectorToReal_effectiveLatticeCoords_eq_top :
    Submodule.span ℝ
      (↑((effectiveLatticeCoords D).image intVectorToReal) :
        Set (Fin (effectiveRank D) → ℝ)) = ⊤ := by
  let H := integerGeneratedSubspace D
  let e : H ≃ₗ[ℝ] Fin (effectiveRank D) → ℝ := integerGeneratedCoordinateEquiv D
  set T : Finset (Fin (effectiveRank D) → ℝ) :=
    (effectiveLatticeCoords D).image intVectorToReal with hT
  set Z : Set H := {p : H | ∃ y ∈ (D : Set (Fin d → ℤ)), ↑p = intVectorToReal y}
  have hT_eq : (T : Set (Fin (effectiveRank D) → ℝ)) = e '' Z := by
    ext x
    constructor
    · intro hx
      rw [hT, Finset.coe_image, effectiveLatticeCoords, Finset.coe_image] at hx
      obtain ⟨v, ⟨y, hyD, rfl⟩, rfl⟩ := hx
      refine ⟨⟨intVectorToReal y, mem_latticeDomain_of_mem D hyD⟩,
        ⟨y, hyD, rfl⟩, ?_⟩
      rw [intVectorToReal_effectiveLatticeMap D
        (mem_latticeDomain_of_mem D hyD)]
      rfl
    · rintro ⟨p, ⟨y, hyD, hp⟩, rfl⟩
      rw [hT, Finset.coe_image, effectiveLatticeCoords, Finset.coe_image]
      refine ⟨effectiveLatticeMap D y, ⟨y, hyD, rfl⟩, ?_⟩
      rw [intVectorToReal_effectiveLatticeMap D
        (mem_latticeDomain_of_mem D hyD)]
      congr 1
      apply Subtype.ext
      exact hp.symm
  have hsubtype_image : H.subtype '' Z = intVectorToReal '' (D : Set (Fin d → ℤ)) := by
    ext x
    constructor
    · rintro ⟨p, ⟨y, hyD, hpy⟩, rfl⟩
      exact ⟨y, hyD, hpy.symm⟩
    · rintro ⟨y, hyD, rfl⟩
      exact ⟨⟨intVectorToReal y, mem_latticeDomain_of_mem D hyD⟩,
        ⟨y, hyD, rfl⟩, rfl⟩
  have hspanZ : Submodule.span ℝ Z = ⊤ := by
    apply Submodule.map_injective_of_injective H.subtype_injective
    rw [Submodule.map_top, Submodule.range_subtype, Submodule.map_span, hsubtype_image]
    rfl
  rw [hT, hT_eq]
  have hmap : Submodule.span ℝ (e '' Z) =
      Submodule.map e.toLinearMap (Submodule.span ℝ Z) :=
    (Submodule.map_span e.toLinearMap Z).symm
  rw [hmap, hspanZ, Submodule.map_top, LinearEquiv.range]

/-- Effective lattice coordinates are full-dimensional when `D` contains the origin. -/
lemma finsetAffineDim_effectiveLatticeCoords (h0 : (0 : Fin d → ℤ) ∈ D) :
    finsetAffineDim ((effectiveLatticeCoords D).image intVectorToReal) = effectiveRank D := by
  let H := integerGeneratedSubspace D
  let e : H ≃ₗ[ℝ] Fin (effectiveRank D) → ℝ := integerGeneratedCoordinateEquiv D
  set T : Finset (Fin (effectiveRank D) → ℝ) :=
    (effectiveLatticeCoords D).image intVectorToReal with hT
  have hmap0 : effectiveLatticeMap D 0 = 0 := by
    rw [effectiveLatticeMap_eq_on D (zero_mem_latticeDomain D),
      latticeEmbed_zero, map_zero]
  have h0T : (0 : Fin (effectiveRank D) → ℝ) ∈ (T : Set _) := by
    rw [hT, Finset.mem_coe, Finset.mem_image]
    refine ⟨effectiveLatticeMap D 0, Finset.mem_image_of_mem _ h0, ?_⟩
    rw [hmap0, intVectorToReal_zero]
  set Z : Set H := {p : H | ∃ y ∈ (D : Set (Fin d → ℤ)), ↑p = intVectorToReal y}
  have hT_eq : (T : Set (Fin (effectiveRank D) → ℝ)) = e '' Z := by
    ext x
    constructor
    · intro hx
      rw [hT, Finset.coe_image, effectiveLatticeCoords, Finset.coe_image] at hx
      obtain ⟨v, ⟨y, hyD, rfl⟩, rfl⟩ := hx
      refine ⟨⟨intVectorToReal y, mem_latticeDomain_of_mem D hyD⟩,
        ⟨y, hyD, rfl⟩, ?_⟩
      rw [intVectorToReal_effectiveLatticeMap D
        (mem_latticeDomain_of_mem D hyD)]
      rfl
    · rintro ⟨p, ⟨y, hyD, hp⟩, rfl⟩
      rw [hT, Finset.coe_image, effectiveLatticeCoords, Finset.coe_image]
      refine ⟨effectiveLatticeMap D y, ⟨y, hyD, rfl⟩, ?_⟩
      rw [intVectorToReal_effectiveLatticeMap D
        (mem_latticeDomain_of_mem D hyD)]
      congr 1
      apply Subtype.ext
      exact hp.symm
  have hsubtype_image : H.subtype '' Z = intVectorToReal '' (D : Set (Fin d → ℤ)) := by
    ext x
    constructor
    · rintro ⟨p, ⟨y, hyD, hpy⟩, rfl⟩
      exact ⟨y, hyD, hpy.symm⟩
    · rintro ⟨y, hyD, rfl⟩
      exact ⟨⟨intVectorToReal y, mem_latticeDomain_of_mem D hyD⟩,
        ⟨y, hyD, rfl⟩, rfl⟩
  have hspanZ : Submodule.span ℝ Z = ⊤ := by
    apply Submodule.map_injective_of_injective H.subtype_injective
    rw [Submodule.map_top, Submodule.range_subtype, Submodule.map_span, hsubtype_image]
    rfl
  have hspanT : Submodule.span ℝ (T : Set (Fin (effectiveRank D) → ℝ)) = ⊤ := by
    rw [hT_eq]
    have hmap : Submodule.span ℝ (e '' Z) =
        Submodule.map e.toLinearMap (Submodule.span ℝ Z) :=
      (Submodule.map_span e.toLinearMap Z).symm
    rw [hmap, hspanZ, Submodule.map_top, LinearEquiv.range]
  have hvspan : vectorSpan ℝ (T : Set (Fin (effectiveRank D) → ℝ)) = ⊤ := by
    rw [vectorSpan_eq_span_vsub_set_right ℝ h0T]
    have heq :
        (fun x ↦ x -ᵥ (0 : Fin (effectiveRank D) → ℝ)) '' (T : Set _) =
          (T : Set _) := by
      ext x
      simp [vsub_eq_sub]
    rw [heq, hspanT]
  rw [hT, finsetAffineDim, direction_affineSpan, hvspan,
    finrank_top, Module.finrank_fin_fun]

/-- Effective coordinates preserve the symmetric-convex-progression structure and eliminate the
original ambient dimension. -/
lemma isSymmetricConvexProgression_effectiveLatticeCoords
    {K : Set (Fin d → ℝ)} (hconv : Convex ℝ K)
    (hsymm : ∀ x, x ∈ K ↔ -x ∈ K)
    (hDK : ∀ v : Fin d → ℤ, v ∈ D ↔ intVectorToReal v ∈ K) :
    IsSymmetricConvexProgression
      (r := effectiveRank D) (effectiveLatticeCoords D) := by
  refine ⟨effectiveLatticeBody D K, convex_effectiveLatticeBody D hconv,
    fun x ↦ ⟨neg_mem_effectiveLatticeBody D hsymm, ?_⟩,
    fun v ↦ mem_effectiveLatticeCoords_iff D hDK,
    finsetAffineDim_le_effectiveRank D⟩
  intro hx
  simpa using neg_mem_effectiveLatticeBody D hsymm hx

end

end DenseSetsWithoutLargeSumsets
